from application.ports.board_repository_port import BoardRepositoryPort
from domain.entities.board_entity import BoardEntity


class SqlAlchemyTaskRepository(BoardRepositoryPort):
    def get_board(self, id: int) -> BoardEntity | None: ...
    def list_boards(self) -> list[BoardEntity]: ...
    def add_board(self, board: BoardEntity) -> BoardEntity: ...
    def update_board(self, board: BoardEntity) -> BoardEntity: ...
    def delete_board(self, board: BoardEntity) -> None: ...
    def commit(self) -> None: ...
