from application.ports.user_repository_port import UserRepositoryPort
from domain.entities.user_entity import UserEntity


class SqlAlchemyUserRepository(UserRepositoryPort):
    def get_user(self, id: int) -> UserEntity | None: ...
    def get_user_by_username(self, username: str) -> UserEntity | None: ...
    def get_users_by_ids(self, ids: list[int]) -> list[UserEntity]: ...
    def list_users(self) -> list[UserEntity]: ...
    def create_user(self, user: UserEntity) -> UserEntity: ...
    def update_user(self, user: UserEntity) -> UserEntity: ...
    def delete_user(self, user: UserEntity) -> None: ...
