from application.ports.task_repository_port import TaskRepositoryPort
from domain.entities.task_entity import TaskEntity


class TaskRepository(TaskRepositoryPort):
    def get_task(self, id: int) -> TaskEntity | None: ...
    def get_all_board_member_tasks(self, board_member_id: int) -> list[TaskEntity]: ...
    def get_all_board_tasks(self, board_id: int) -> list[TaskEntity]: ...
    def list_tasks(self) -> list[TaskEntity]: ...
    def create_task(self, task: TaskEntity) -> TaskEntity: ...
    def create_new_board_task(self, task: TaskEntity, board_id: int) -> TaskEntity: ...
    def update_task(self, task: TaskEntity) -> TaskEntity: ...
    def delete_task(self, task: TaskEntity) -> None: ...
