"""add created_at to tasks and boards

Revision ID: d3e2af3482cc
Revises: c4227e9101a0
Create Date: 2026-06-22 19:07:59.877368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e2af3482cc'
down_revision: Union[str, Sequence[str], None] = 'c4227e9101a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_at')
    op.drop_column('boards', 'created_at')
    # ### end Alembic commands ###
