from domain.entities.board_entity import BoardEntity
from dtos.board import BoardCreate


class BoardRepositoryPort:
    def get_board(self, id: int) -> BoardEntity | None: ...
    def list_boards(self) -> list[BoardEntity]: ...
    def add_board(self, board: BoardCreate) -> BoardEntity: ...
    def update_board(self, board: BoardEntity) -> BoardEntity: ...
    def delete_board(self, board: BoardEntity) -> None: ...
    def commit(self) -> None: ...
