from domain.entities.task_entity import TaskEntity
from domain.value_objects.task.new_task import NewTask
from domain.value_objects.task.task_patch import TaskPatch


class TaskRepositoryPort:
    def get_task(self, id: int) -> TaskEntity: ...
    def get_all_board_member_tasks(
        self, board_id: int, user_id: int
    ) -> list[TaskEntity]: ...
    def get_all_board_tasks(self, board_id: int) -> list[TaskEntity]: ...
    def list_tasks(self) -> list[TaskEntity]: ...
    def create_board_task(self, new_task: NewTask) -> TaskEntity: ...
    def update_task(self, task_patch: TaskPatch) -> TaskEntity: ...
    def delete_task(self, task_id: int) -> None: ...
