"""add hashed_password field to users

Revision ID: 3260cb28c177
Revises: f93becebbdd0
Create Date: 2026-06-30 19:02:06.581220

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3260cb28c177"
down_revision: Union[str, Sequence[str], None] = "f93becebbdd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=255)))
    op.execute("UPDATE users SET hashed_password = '' WHERE hashed_password IS NULL")
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("hashed_password", nullable=False)
    op.drop_index(op.f("ix_users_id"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###
